name: cicd_mlops

trigger:
  branches:
    include:
    - main

stages:
- stage: CI
  jobs:
    - job:
      displayName: CI
      pool:
        vmImage: ubuntu-latest
      steps:
      - script: pip install -r ./azure-ci/requirements.txt
        displayName: 'Prepare Environment'

      - script: echo "Hello, world!"
        displayName: 'Lint'

      - script: echo "Hello, world!"
        displayName: 'Unit Tests'

      - script: echo "Hello, world!"
        displayName: 'Integration Tests'

      - script: python3 ./pipeline/build_pipeline.py
        displayName: 'Build and Run Training Pipeline'
        env:
          AZURE_TENANT_ID: $(tenant)
          AZURE_CLIENT_ID: $(client)
          AZURE_CLIENT_SECRET: $(secret)

      - script: echo "Hello, world!"
        displayName: 'Compare Models + Promote'

      - script: echo "Hello, world!"
        displayName: 'Deploy Model'

      - script: ls
        displayName: 'Run some more bash'
