name: cicd_mlops

trigger:
  branches:
    include:
    - main

stages:
- stage: CI
  jobs:
    - job:
      displayName: CI
      pool:
        vmImage: ubuntu-latest
      steps:
      - script: echo "Hello, world!"
        displayName: 'Lint'

      - script: echo "Hello, world!"
        displayName: 'Unit Tests'

      - script: echo "Hello, world!"
        displayName: 'Integration Tests'

      - script: echo "Hello, world!"
        displayName: 'Build Training Pipeline'

      - script: echo "Hello, world!"
        displayName: 'Run Training Pipeline'

      - script: echo "Hello, world!"
        displayName: 'Compare Models + Promote'

      - script: echo "Hello, world!"
        displayName: 'Deploy Model'

      - script: ls
        displayName: 'Run some more bash'
