name: cicd_mlops

trigger:
  branches:
    include:
    - main

stages:
- stage: CI
  jobs:
    - job:
      displayName: CI
      pool:
        vmImage: ubuntu-latest
      steps:
      - script: echo Hello, world!
        displayName: 'Run some bash'

      - script: ls
        displayName: 'Run some more bash'
